# Generated by Django 4.1.5 on 2023-04-04 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=300)),
                ('premiere_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('premiere_date', models.DateField()),
                ('episodes', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_series.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('premiere_date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('season', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_series.season')),
            ],
        ),
    ]
