# Generated by Django 4.1.5 on 2023-04-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='season',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
