# Generated by Django 4.1.5 on 2023-04-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_series', '0002_episode_number_season_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='season',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='is_published',
        ),
        migrations.AddField(
            model_name='season',
            name='serie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='app_series.serie'),
        ),
        migrations.AddField(
            model_name='serie',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'published'), ('n', 'not published')], default='n', help_text='pub status', max_length=1),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='app_series.season'),
        ),
        migrations.AddField(
            model_name='serie',
            name='gender',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_series.gender'),
        ),
    ]
