# Generated by Django 4.1.5 on 2023-04-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_series', '0003_gender_remove_season_episodes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='gender',
        ),
        migrations.AddField(
            model_name='serie',
            name='gender',
            field=models.ManyToManyField(to='app_series.gender'),
        ),
    ]
