# Generated by Django 4.1.5 on 2023-04-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_series', '0004_remove_serie_gender_serie_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='gender',
            new_name='genders',
        ),
    ]
