# Generated by Django 4.1.5 on 2023-04-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_series', '0005_rename_gender_serie_genders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='genders',
            field=models.ManyToManyField(related_name='series', to='app_series.gender'),
        ),
    ]
