# Generated by Django 4.1.5 on 2023-04-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_series', '0010_platform_serie_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='genders',
            field=models.ManyToManyField(related_name='genders', to='app_series.gender'),
        ),
    ]
