# Generated by Django 4.1.5 on 2023-04-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_series', '0012_alter_serie_genders_alter_serie_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='poster',
            field=models.ImageField(blank=True, default='', upload_to='app_series/poster/%Y/%m/%d/'),
        ),
    ]
